services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  aegis:
    build: .
    command: node server.js
    ports:
      - "3000:3000"
    env_file:
      - .env.docker

  websocket-server:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis-pub-sub

  redis-pub-sub:
    build:
      context: ./redis-pub-sub
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      REDIS_URL: redis://redis:6379
